image: node:latest

stages:
  - build

job1: 
  stage: build
  script: 
    - npm install --include=dev
    - npm run build
    - tsc main.ts
    - node main.js
  artifacts:
    paths:
      - shacl.ttl
      - turleTranslation.ttl
   