image: node:latest

stages:
  - build

job1: 
  stage: build
  script: 
    - npm install --include=dev
    - npm install -g typescript
    - npm run build
    - node main.js
  #artifacts:
  #  paths:
  #    - build/shacl.ttl
  #    - build/turtleTranslation.ttl
   
